---
- name: Install  & config log server
  hosts: log
  vars_files:
   - secrets.yml
  become: true
  tasks:

   - name: Update apt package cache
     ansible.builtin.apt:
      update_cache: true

   - name: Install systemd-journal-remote
     ansible.builtin.apt:
      name: "{{ item }}"
      state: present
     loop:
      - systemd-journal-remote

   - name: Create directory for logs
     ansible.builtin.file:
      path: /var/log/journal/remote
      state: directory
      owner: systemd-journal-remote
      group: systemd-journal-remote
      mode: '0777'

   - name: Replace https to http
     ansible.builtin.lineinfile:
      path: /lib/systemd/system/systemd-journal-remote.service
      regexp: '^ExecStart=.*'
      line: 'ExecStart=/usr/lib/systemd/systemd-journal-remote --listen-http=-3 --output=/var/log/journal/remote/'

   - name: Reload systemd configuration
     ansible.builtin.systemd:
        daemon_reload: true

   - name: Enable service httpd, and not touch the state
     ansible.builtin.service:
      name: systemd-journal-remote
      enabled: true

   - name: Start journaled remote service
     ansible.builtin.service:
      name: systemd-journal-remote
      state: started

   - name: Copy deb files
     ansible.builtin.copy:
      src: /home/jecka/elk/
      dest: /tmp/
   

   
...