---
- name: Install  & config elk
  hosts: elk
  vars_files:
   - secrets.yml
  become: true
  tasks:

   - name: Update apt package cache
     ansible.builtin.apt:
      update_cache: true

   - name: Copy deb files
     ansible.builtin.copy:
      src: /home/jecka/elk/
      dest: /tmp/

   - name: Install elk debs
     ansible.builtin.apt:
      deb: "{{ item }}"
     loop:
     - /tmp/elasticsearch-9.1.2-amd64.deb
     - /tmp/logstash-9.1.2-amd64.deb
     - /tmp/kibana-9.1.2-amd64.deb
     - /tmp/filebeat-9.1.2-amd64.deb

   - name: Copy configs for elk
     ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/jecka2/installation/refs/heads/main/configs/log_mon/kibana.yml
      dest: /etc/kibana/kibana.yml

   - name: Copy configs for elk
     ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/jecka2/installation/refs/heads/main/configs/log_mon/logstash.yml
      dest: /etc/logstash/logstash.yml
      
   - name: Copy configs for elk
     ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/jecka2/installation/refs/heads/main/configs/log_mon/elasticsearch.yml
      dest: /etc/elasticsearch/elasticsearch.yml

   - name: Copy configs for elk
     ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/jecka2/installation/refs/heads/main/configs/log_mon/logstash-nginx-es.conf
      dest: /etc/logstash/conf.d/logstash-nginx-es.conf

   - name: Copy configs for elk
     ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/jecka2/installation/refs/heads/main/configs/log_mon/filebeat.yml
      dest: /etc/filebeat/filebeat.yml  


   - name: Replace https to http
     ansible.builtin.lineinfile:
      path: /etc/elasticsearch/elasticsearch.yml
      regexp: 'cluster.initial_master_nodes: ["mon-log"]'
      line: 'cluster.initial_master_nodes: ["elk"]'

   - name: Enable Nginx module using filebeat command
     ansible.builtin.command:
      cmd: filebeat modules enable nginx
     args:
      creates: /etc/filebeat/modules.d/nginx.yml

   #- name: Enable Nginx module in Filebeat
   #  ansible.builtin.command: "/usr/share/filebeat/bin/filebeat modules enable nginx"

   - name: Enable service httpd, and not touch the state
     ansible.builtin.service:
      name: "{{ item }}"
      enabled: true
     loop:
       - kibana
       - logstash
       - filebeat
       - elasticsearch 

   - name: Start journaled remote service
     ansible.builtin.service:
       name: "{{ item }}"
       state: 'started' 
     loop:
      - kibana
      - logstash
      - filebeat
      - elasticsearch 
...