---
- name: Create vms on Proxmox
  hosts: Proxmox
  vars_files:
    - secrets.yml
  vars:
   vms_ip_addresses:
   - ip_address: "192.168.1.101"
   - ip_address: "192.168.1.102"
   - ip_address: "192.168.1.103"
   - ip_address: "192.168.1.104"
   vms_names:
   - name: web
   - name: log
   - name: elk
   - name: test

  tasks:
    - name: Install python
      ansible.builtin.apt:
        name: python3-pip
        state: present

    - name: INstall pip modules
      ansible.builtin.apt:
       name:  python3-setuptools
       state: present

    - name: Install pip modules 
      ansible.builtin.apt:
        name: python3-requests
        state: present

    - name: Install pip modules
      ansible.builtin.apt:
        name: python3-proxmoxer
        state: present

    - name: clone KVM VM 1 from template
      community.general.proxmox_kvm:
        node: "pve"  # Узел кластера (можно указать all)
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_token_id: "{{ proxmox_token }}"
        api_token_secret: "{{ proxmox_token_secret }}"
        validate_certs: false
        clone: "init"
        name: "{{ item.0.name }}"
        net:
         net0: 'virtio,bridge=vmbr1'
        ipconfig:
           ipconfig0: "ip={{item.1.ip_address}} gw=192.168.1.1"
        force: true
        storage: "homelab"
        timeout: 300
      loop: "{{ vms_names | zip(vms_ip_addresses) }}"


    - name: Start VM
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_token_id: "{{ proxmox_token }}"
        api_token_secret: "{{ proxmox_token_secret }}"
        name: "{{ item.name }}"
        node: "pve"
        state: started   
      loop: "{{ vms_names }}"   
      
...