---
gateway : "192.168.1.1"
dns: "192.168.1.148"

vms_to_create:
 - name: "web"
   ip_address: "192.168.1.101/24"
   memory: "1024"

 - name: "log"
   ip_address: "192.168.1.102/24"
   memory: "1024"

 - name: "elk"
   ip_address: "192.168.1.103/24"
   memory: "8096"

